### ISSUE TITLE
Error when clicking on Docker CLI button 

### ISSUE THREAD

**Issue by AndreyAntipov** [kitematic/kitematic#1154]
Host: OS X 10.11

Debugger warnings:
```js
Unhandled rejection Error: /Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/terminal DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/andreyantipov/.docker/machine/machines/default DOCKER_TLS_VERIFY=1 /bin/zsh returned non zero exit code. Stderr: 69:77: syntax error: Expected class name but found identifier. (-2741)
92:124: execution error: System Events got an error: Application isn’t running. (-600)

    at /Applications/Docker/Kitematic (Beta).app/Contents/Resources/app.asar/utils/Util.js:52:18
    at ChildProcess.<anonymous> (/Applications/Docker/Kitematic (Beta).app/Contents/Resources/app.asar/node_modules/exec/exec.js:91:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
Which are open a new terminal without DOCKER_* variables. How i can avoid this problem?

**Comment by FrenchBen** [comment]
@AndreyAntipov Can you walk me through the steps you took to create this error?

**Comment by AndreyAntipov** [comment]
Problem is solved. Just rebooted machine and reinstall docker

**Comment by FrenchBen** [comment]
:+1:
