### ISSUE TITLE
Docker CLI Button does nothing

### ISSUE THREAD

**Issue by robinduckett** [kitematic/kitematic#564]
Well, not nothing. A cursory look in the Dev Tools reveals the following log:

```
Unhandled rejection Error: /Applications/Kitematic (Beta).app/Contents/Resources/app/resources/terminal DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/robin/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 $SHELL returned non zero exit code. Stderr: 465:465: syntax error: Expected “"” but found end of script. (-2741)

    at /Applications/Kitematic (Beta).app/Contents/Resources/app/build/utils/Util.js:16:18
    at ChildProcess.<anonymous> (/Applications/Kitematic (Beta).app/Contents/Resources/app/node_modules/exec/exec.js:91:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:996:16)
    at Socket.<anonymous> (child_process.js:1165:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe._onclose (net.js:464:12)
```

I'm not sure if this is an error with my machine, or some kind of setup error, but I've reinstalled the app, and it still doesn't work.

**Comment by goloroden** [comment]
I guess this is a duplicate of #563, isn't it?

**Comment by robinduckett** [comment]
You are correct, sir.
